---
deployment:
	tasks:
		- export DEPLOYPATH="$HOME/kylewells/public_html"
		- /bin/mkdir -p "$DEPLOYPATH"
		# Ensure Ruby, Bundler, and Jekyll are available (install to user gem path if missing)
		- |
			if ! command -v ruby >/dev/null 2>&1; then
				echo "Ruby is not available on this server. Enable Ruby in cPanel (Setup Ruby App) or contact your host." >&2
				exit 1
			fi
			# Configure user gem path and ensure it's on PATH
			RUBY_VER_DIR=$(ruby -e 'require "rbconfig"; print RbConfig::CONFIG["ruby_version"]')
			export GEM_HOME="$HOME/.gem/ruby/$RUBY_VER_DIR"
			export GEM_PATH="$GEM_HOME"
			export PATH="$HOME/.gem/ruby/$RUBY_VER_DIR/bin:$PATH"
			if ! command -v bundle >/dev/null 2>&1; then
				echo "Installing Bundler to user gem path..."
				gem install --user-install bundler --no-document || { echo "Failed to install Bundler" >&2; exit 1; }
			fi
			if ! command -v jekyll >/dev/null 2>&1; then
				echo "Installing Jekyll to user gem path..."
				gem install --user-install jekyll --no-document || { echo "Failed to install Jekyll" >&2; exit 1; }
			fi
		# Build the site on the server if _site is missing
		- |
			if [ ! -d "_site" ]; then
				echo "Building site (production)..."
				if command -v bundle >/dev/null 2>&1; then
					JEKYLL_ENV=production bundle exec jekyll build -d _site || { echo "bundle exec jekyll build failed" >&2; exit 1; }
				else
					JEKYLL_ENV=production jekyll build -d _site || { echo "jekyll build failed" >&2; exit 1; }
				fi
			fi
		# Deploy only the contents of _site to public_html (delete removed files)
		- /usr/bin/rsync -a --delete _site/ "$DEPLOYPATH/"