---
deployment:
  tasks:
    - export DEPLOYPATH="$HOME/public_html"
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/cp -a _site/. "$DEPLOYPATH/"
      - /bin/cp -R /home/kylewells/repositories/clevelandsorcery/_site/* $DEPLOYPATH